export const chinaProvinces = [
  { id: "Anhui", name: "Anhui" },
  { id: "Beijing", name: "Beijing" },
  { id: "Chongqing", name: "Chongqing" },
  { id: "Fujian", name: "Fujian" },
  { id: "Gansu", name: "Gansu" },
  { id: "Guangdong", name: "Guangdong" },
  { id: "Guangxi", name: "Guangxi" },
  { id: "Guizhou", name: "Guizhou" },
  { id: "Hainan", name: "Hainan" },
  { id: "Hebei", name: "Hebei" },
  { id: "Heilongjiang", name: "Heilongjiang" },
  { id: "Henan", name: "Henan" },
  { id: "Hubei", name: "Hubei" },
  { id: "Hunan", name: "Hunan" },
  { id: "Inner Mongol", name: "Inner Mongol" },
  { id: "Jiangsu", name: "Jiangsu" },
  { id: "Jiangxi", name: "Jiangxi" },
  { id: "Jilin", name: "Jilin" },
  { id: "Liaoning", name: "Liaoning" },
  { id: "Ningxia", name: "Ningxia" },
  { id: "Qinghai", name: "Qinghai" },
  { id: "Shaanxi", name: "Shaanxi" },
  { id: "Shandong", name: "Shandong" },
  { id: "Shanghai", name: "Shanghai" },
  { id: "Shanxi", name: "Shanxi" },
  { id: "Sichuan", name: "Sichuan" },
  { id: "Tianjin", name: "Tianjin" },
  { id: "Xinjiang", name: "Xinjiang" },
  { id: "Xizang", name: "Xizang" },
  { id: "Yunnan", name: "Yunnan" },
  { id: "Zhejiang", name: "Zhejiang" }
]
