// Country data extracted from world.svg
// Maps country codes/IDs to full country names

export interface Country {
  id: string;  // The ID or class from the SVG
  name: string; // Full country name
}

export const countries: Country[] = [
  { id: "AF", name: "Afghanistan" },
  { id: "Angola", name: "Angola" },
  { id: "AL", name: "Albania" },
  { id: "AE", name: "United Arab Emirates" },
  { id: "Argentina", name: "Argentina" },
  { id: "AM", name: "Armenia" },
  { id: "Australia", name: "Australia" },
  { id: "AT", name: "Austria" },
  { id: "Azerbaijan", name: "Azerbaijan" },
  { id: "BI", name: "Burundi" },
  { id: "BE", name: "Belgium" },
  { id: "BJ", name: "Benin" },
  { id: "BF", name: "Burkina Faso" },
  { id: "BD", name: "Bangladesh" },
  { id: "BG", name: "Bulgaria" },
  { id: "BA", name: "Bosnia and Herzegovina" },
  { id: "BY", name: "Belarus" },
  { id: "BZ", name: "Belize" },
  { id: "BO", name: "Bolivia" },
  { id: "BR", name: "Brazil" },
  { id: "BN", name: "Brunei" },
  { id: "BT", name: "Bhutan" },
  { id: "BW", name: "Botswana" },
  { id: "CF", name: "Central African Republic" },
  { id: "Canada", name: "Canada" },
  { id: "CH", name: "Switzerland" },
  { id: "CL", name: "Chile" },
  { id: "China", name: "China" },
  { id: "CI", name: "Côte d'Ivoire" },
  { id: "CM", name: "Cameroon" },
  { id: "CD", name: "Democratic Republic of the Congo" },
  { id: "CG", name: "Republic of Congo" },
  { id: "CO", name: "Colombia" },
  { id: "CR", name: "Costa Rica" },
  { id: "CU", name: "Cuba" },
  { id: "CZ", name: "Czech Republic" },
  { id: "DE", name: "Germany" },
  { id: "DJ", name: "Djibouti" },
  { id: "DK", name: "Denmark" },
  { id: "DO", name: "Dominican Republic" },
  { id: "DZ", name: "Algeria" },
  { id: "EC", name: "Ecuador" },
  { id: "EG", name: "Egypt" },
  { id: "ER", name: "Eritrea" },
  { id: "ES", name: "Spain" },
  { id: "EE", name: "Estonia" },
  { id: "ET", name: "Ethiopia" },
  { id: "FI", name: "Finland" },
  { id: "FJ", name: "Fiji" },
  { id: "Falkland Islands", name: "Falkland Islands" },
  { id: "FR", name: "France" },
  { id: "FP", name: "French Polynesia" },
  { id: "GA", name: "Gabon" },
  { id: "GB", name: "United Kingdom" },
  { id: "GE", name: "Georgia" },
  { id: "GH", name: "Ghana" },
  { id: "GN", name: "Guinea" },
  { id: "GM", name: "Gambia" },
  { id: "GW", name: "Guinea-Bissau" },
  { id: "GQ", name: "Equatorial Guinea" },
  { id: "GR", name: "Greece" },
  { id: "GL", name: "Greenland" },
  { id: "GT", name: "Guatemala" },
  { id: "GY", name: "Guyana" },
  { id: "HN", name: "Honduras" },
  { id: "HR", name: "Croatia" },
  { id: "HT", name: "Haiti" },
  { id: "HU", name: "Hungary" },
  { id: "Indonesia", name: "Indonesia" },
  { id: "IN", name: "India" },
  { id: "IE", name: "Ireland" },
  { id: "IR", name: "Iran" },
  { id: "IQ", name: "Iraq" },
  { id: "IS", name: "Iceland" },
  { id: "IL", name: "Israel" },
  { id: "IT", name: "Italy" },
  { id: "JM", name: "Jamaica" },
  { id: "JO", name: "Jordan" },
  { id: "JP", name: "Japan" },
  { id: "KZ", name: "Kazakhstan" },
  { id: "KE", name: "Kenya" },
  { id: "KG", name: "Kyrgyzstan" },
  { id: "KH", name: "Cambodia" },
  { id: "KR", name: "South Korea" },
  { id: "KW", name: "Kuwait" },
  { id: "LA", name: "Laos" },
  { id: "LB", name: "Lebanon" },
  { id: "LR", name: "Liberia" },
  { id: "LY", name: "Libya" },
  { id: "LK", name: "Sri Lanka" },
  { id: "LS", name: "Lesotho" },
  { id: "LT", name: "Lithuania" },
  { id: "LU", name: "Luxembourg" },
  { id: "LV", name: "Latvia" },
  { id: "MA", name: "Morocco" },
  { id: "MD", name: "Moldova" },
  { id: "MG", name: "Madagascar" },
  { id: "Mexico", name: "Mexico" },
  { id: "MK", name: "Macedonia" },
  { id: "ML", name: "Mali" },
  { id: "MM", name: "Myanmar" },
  { id: "ME", name: "Montenegro" },
  { id: "MN", name: "Mongolia" },
  { id: "MZ", name: "Mozambique" },
  { id: "MR", name: "Mauritania" },
  { id: "MW", name: "Malawi" },
  { id: "Malaysia", name: "Malaysia" },
  { id: "NA", name: "Namibia" },
  { id: "NC", name: "New Caledonia" },
  { id: "NE", name: "Niger" },
  { id: "NG", name: "Nigeria" },
  { id: "NI", name: "Nicaragua" },
  { id: "NL", name: "Netherlands" },
  { id: "NO", name: "Norway" },
  { id: "NP", name: "Nepal" },
  { id: "NZ", name: "New Zealand" },
  { id: "OM", name: "Oman" },
  { id: "PK", name: "Pakistan" },
  { id: "PA", name: "Panama" },
  { id: "PE", name: "Peru" },
  { id: "PH", name: "Philippines" },
  { id: "PG", name: "Papua New Guinea" },
  { id: "PL", name: "Poland" },
  { id: "PR", name: "Puerto Rico" },
  { id: "KP", name: "North Korea" },
  { id: "PT", name: "Portugal" },
  { id: "PY", name: "Paraguay" },
  { id: "QA", name: "Qatar" },
  { id: "RO", name: "Romania" },
  { id: "RU", name: "Russian Federation" },
  { id: "RW", name: "Rwanda" },
  { id: "Western Sahara", name: "Western Sahara" },
  { id: "SA", name: "Saudi Arabia" },
  { id: "SD", name: "Sudan" },
  { id: "SS", name: "South Sudan" },
  { id: "SN", name: "Senegal" },
  { id: "SB", name: "Solomon Islands" },
  { id: "SL", name: "Sierra Leone" },
  { id: "SV", name: "El Salvador" },
  { id: "SO", name: "Somalia" },
  { id: "RS", name: "Serbia" },
  { id: "SR", name: "Suriname" },
  { id: "SK", name: "Slovakia" },
  { id: "SI", name: "Slovenia" },
  { id: "SE", name: "Sweden" },
  { id: "SZ", name: "Swaziland" },
  { id: "SY", name: "Syria" },
  { id: "TD", name: "Chad" },
  { id: "TG", name: "Togo" },
  { id: "TH", name: "Thailand" },
  { id: "TJ", name: "Tajikistan" },
  { id: "TM", name: "Turkmenistan" },
  { id: "TL", name: "Timor-Leste" },
  { id: "TN", name: "Tunisia" },
  { id: "TR", name: "Turkey" },
  { id: "TW", name: "Taiwan" },
  { id: "TZ", name: "Tanzania" },
  { id: "UG", name: "Uganda" },
  { id: "UA", name: "Ukraine" },
  { id: "UY", name: "Uruguay" },
  { id: "US", name: "United States of America" },
  { id: "UZ", name: "Uzbekistan" },
  { id: "VE", name: "Venezuela" },
  { id: "VN", name: "Vietnam" },
  // { id: "VU", name: "Vanuatu" }, // TODO: small islands not visible on map
  { id: "PS", name: "West Bank" },
  { id: "YE", name: "Yemen" },
  { id: "ZA", name: "South Africa" },
  { id: "ZM", name: "Zambia" },
  { id: "ZW", name: "Zimbabwe" }
];

// Helper function to get a random country
export function getRandomCountry(): Country {
  return countries[Math.floor(Math.random() * countries.length)];
}

// Helper function to find country by data-country attribute
export function findCountryByElement(element: SVGElement): Country | null {
  const path = element.closest('path') as SVGPathElement | null;
  const target = path ?? element;
  const dataCountry = target.getAttribute('data-country')?.trim();
  const id = target.getAttribute('id')?.trim();

  if (!dataCountry && !id) return null;

  return countries.find(c => (
    (id && c.id === id) ||
    (dataCountry && c.name === dataCountry) ||
    (dataCountry && c.id === dataCountry)
  )) || null;
}
