export const indiaStates = [
  { id: "Andaman and Nicobar", name: "Andaman and Nicobar" },
  { id: "Andhra Pradesh", name: "Andhra Pradesh" },
  { id: "Arunachal Pradesh", name: "Arunachal Pradesh" },
  { id: "Assam", name: "Assam" },
  { id: "Bihar", name: "Bihar" },
  { id: "Chandigarh", name: "Chandigarh" },
  { id: "Chhattisgarh", name: "Chhattisgarh" },
  { id: "Dadra and Nagar Haveli and Daman and Diu", name: "Dadra and Nagar Haveli and Daman and Diu" },
  { id: "Delhi", name: "Delhi" },
  { id: "Goa", name: "Goa" },
  { id: "Gujarat", name: "Gujarat" },
  { id: "Haryana", name: "Haryana" },
  { id: "Himachal Pradesh", name: "Himachal Pradesh" },
  { id: "Jammu and Kashmir", name: "Jammu and Kashmir" },
  { id: "Jharkhand", name: "Jharkhand" },
  { id: "Karnataka", name: "Karnataka" },
  { id: "Kerala", name: "Kerala" },
  { id: "Ladakh", name: "Ladakh" },
  { id: "Lakshadweep", name: "Lakshadweep" },
  { id: "Madhya Pradesh", name: "Madhya Pradesh" },
  { id: "Maharashtra", name: "Maharashtra" },
  { id: "Manipur", name: "Manipur" },
  { id: "Meghalaya", name: "Meghalaya" },
  { id: "Mizoram", name: "Mizoram" },
  { id: "Nagaland", name: "Nagaland" },
  { id: "Odisha", name: "Odisha" },
  { id: "Puducherry", name: "Puducherry" },
  { id: "Punjab", name: "Punjab" },
  { id: "Rajasthan", name: "Rajasthan" },
  { id: "Sikkim", name: "Sikkim" },
  { id: "Tamil Nadu", name: "Tamil Nadu" },
  { id: "Telangana", name: "Telangana" },
  { id: "Tripura", name: "Tripura" },
  { id: "Uttar Pradesh", name: "Uttar Pradesh" },
  { id: "Uttarakhand", name: "Uttarakhand" },
  { id: "West Bengal", name: "West Bengal" }
]
